library(dplyr)
library(parallel)
source('functions.R')
load("../data/usrds.RData")
cl <- makeCluster(rep_circinus(c(28, 35, 37, 39, 40, 41, 43, 46, 47), length = 124))
teval <- rbind(cbind(1:359, 359:1), cbind(1:899, 899:1), cbind(1:1439, 1439:1))
fit <- data %>% with(kereg_fit(cbind(1, primary == 0, race == 1, diabetes, heart_disease), log(daily_claim / 1000 + 1), cbind(day_since_entry, died_day - day_since_entry), 10, adaptive = T))
res <- data %>% with(log(daily_claim / 1000 + 1) - rowSums(cbind(1, primary == 0, race == 1, diabetes, heart_disease) * fit$coef))
fit <- data %>% with(kereg_fitci(cbind(1, primary == 0, race == 1, diabetes, heart_disease), log(daily_claim / 1000 + 1), cbind(day_since_entry, died_day - day_since_entry), 10, pseudo_id, res, teval))
save(fit, file = 'pseudo_full_result.RData')
